/*
 * uCloud API collection
 *
 * uCloud is a collection of image APIs.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: help@bps-eng.co.ir
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

namespace Bps.uCloud.API.Controllers
{
    using Bps.uCloud.API.Attributes;
    using Bps.uCloud.API.Settings;
    using Microsoft.AspNetCore.Mvc;
    using Swashbuckle.AspNetCore.Annotations;
    using System;
    using System.IO;

    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DefaultApiController : ControllerBase
    {
        #region Fields

        IAppSettings app;

        #endregion

        #region Constructor

        public DefaultApiController(IAppSettings app)
        {
            this.app = app;
        }

        #endregion

        #region Methods

        /// <summary>
        /// Get logo
        /// </summary>
        /// <remarks>Returns the logo image</remarks>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/ucloud/v1/logo")]
        [ValidateModelState]
        [SwaggerOperation("LogoGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(byte[]), description: "OK")]
        public virtual IActionResult LogoGet()
        { 
            var logoPath = Path.Combine(app.RootPath, "images/logo.png");
            var bytes = System.IO.File.ReadAllBytes(logoPath);
            return Ok(bytes);
        }

        /// <summary>
        /// Server heartbeat operation
        /// </summary>
        /// <remarks>This operation shows how to override the global security defined above, as we want to open it up for all users.</remarks>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/ucloud/v1/ping")]
        [ValidateModelState]
        [SwaggerOperation("PingGet")]
        public virtual IActionResult PingGet()
        {
            return Ok(string.Format($"hello, it's {DateTime.UtcNow.ToString("u")}"));
        }

        #endregion

    }
}
