/*
 * uCloud API collection
 *
 * uCloud is a collection of image APIs.
 *
 * OpenAPI spec version: 1.0.2
 * Contact: help@bps-eng.co.ir
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
namespace Bps.uCloud.API.Models
{
    public interface IBarcode
    {
        string Data { get; set; }
        string Location { get; set; }
        string Type { get; set; }
    }
}